//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HITCOUNT
    {
        public decimal ID { get; set; }
        public Nullable<decimal> HOME { get; set; }
        public Nullable<decimal> ABOUT { get; set; }
        public Nullable<decimal> CONTACT { get; set; }
        public Nullable<decimal> DOWNLOADS { get; set; }
        public Nullable<decimal> SECURITY { get; set; }
    }
}
