//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class QUERY
    {
        public decimal Q_ID { get; set; }
        public string ASSIGN_TIME { get; set; }
        public string SOLVE_TIME { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM yy}")]
        public Nullable<System.DateTime> ASSIGN_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string OFFICE { get; set; }
        public Nullable<decimal> EMP_ID { get; set; }
        public string STATUS { get; set; }
        public string COMMENTS { get; set; }
        public string USER_ID { get; set; }
        public string CREATEDTIME { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM yy}")]
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string USER_EMAIL { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM yy}")]
        public Nullable<System.DateTime> SOLVE_DATE { get; set; }
    }
}
