//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public decimal EMP_ID { get; set; }
        public string USER_NAME { get; set; }
        public string EMAIL { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_TYPE { get; set; }
        public string STATUS { get; set; }
        public string RESER_PASSWORD_CODE { get; set; }
    }
}
